apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: basic-quarkus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: basic-quarkus
    app.kubernetes.io/part-of: ann-marie-test
  name: basic-quarkus
  namespace: application-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: basic-quarkus
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: basic-quarkus
    spec:
      containers:
      - image: quay.io/afred/gitops-preview:application-service-basic-quarkus
        imagePullPolicy: Always
        name: container-image
        resources:
          requests:
            cpu: 35m
            memory: 512Mi
status: {}
